#!/bin/bash
cmode="light"
echo "-- $cmode mode"
if (echo $LANG | grep -q "fr") then codlang="fr"
elif (echo $LANG | grep -q "de") then codlang="de"
elif (echo $LANG | grep -q "ru") then codlang="ru"
else codlang="en";fi
foldpix="$codlang""_""$cmode"
foldproj="proj_""$cmode"
foldscripts="scripts_""$codlang"
iconbase="actioncenter_icon_""$cmode"".png"
mkdir -p /opt/trinity/share/apps/actioncenter_applet
sudo tar -xzvf /usr/lib/actioncenter/actioncenter_assets.tar.gz -C /opt/trinity/share/apps/actioncenter_applet/ --wildcards --strip-components=1 "$foldpix"/*
sudo tar -xzvf /usr/lib/actioncenter/actioncenter_assets.tar.gz -C /opt/trinity/share/apps/actioncenter_applet/ --wildcards --strip-components=1 "$foldproj"/*
sudo tar -xzvf /usr/lib/actioncenter/actioncenter_assets.tar.gz -C /opt/trinity/share/apps/actioncenter_applet/ --wildcards --strip-components=1 "$foldscripts"/*
sudo tar -xzvf /usr/lib/actioncenter/actioncenter_assets.tar.gz -C /opt/trinity/share/apps/actioncenter_applet/ "$iconbase"
mv -f /opt/trinity/share/apps/actioncenter_applet/$iconbase /opt/trinity/share/apps/actioncenter_applet/actioncenter.png
>/usr/lib/actioncenter/actioncenter_assets.tar.gz



